[workspace]
members = ["client", "server", "common", "matchmaker"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license-file = "LICENSE.txt"
description = "A multiplayer game built in Rust"

[workspace.dependencies]
base64 = "0.22.1"
dotenvy = "0.15.7"
bincode = { version = "2.0.1", features = ["serde"] }
common = { path = "./common" }
crossterm = "0.29.0"
glam = { version = "0.27.0", features = ["serde"] }
rand = "0.9.3"
renet = "1.2.0"
renet_netcode = "1.2.0"
serde = { version = "1.0.228", features = ["derive"] }