use common::input::{
    A_KEY_HELD, A_KEY_PRESSED, D_KEY_HELD, D_KEY_PRESSED, DOWN_KEY_HELD, DOWN_KEY_PRESSED,
    LEFT_KEY_HELD, LEFT_KEY_PRESSED, RIGHT_KEY_HELD, RIGHT_KEY_PRESSED, S_KEY_HELD, S_KEY_PRESSED,
    SPACE_KEY_HELD, SPACE_KEY_PRESSED, UP_KEY_HELD, UP_KEY_PRESSED, W_KEY_HELD, W_KEY_PRESSED,
    has_input,
};
