name: Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - deploy_itch

jobs:
  deploy-itch:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yaml
          branch: main
          path: assets

      - name: Download butler
        run: |
          curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler

      - name: Fix Permissions
        run: |
          find assets -name '*.AppImage' -exec chmod +x {} \;

      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          GAME: ${{ secrets.ITCH_USERNAME }}/${{ secrets.ITCH_GAME }}
        run: |
          shopt -s nullglob

          for file in assets/windows-package/*.zip; do
            ./butler push "$file" $GAME:windows
          done

          for file in assets/linux-packages/*.AppImage; do
            ./butler push "$file" $GAME:linux
          done

          for file in assets/linux-packages/*.deb; do
            ./butler push "$file" $GAME:linux-deb
          done

          for file in assets/linux-packages/*.rpm; do
            ./butler push "$file" $GAME:linux-rpm
          done

          for file in assets/macos-packages/*.zip; do
            if [[ "$file" == *"intel"* ]] || [[ "$file" == *"x86_64"* ]]; then
              ./butler push "$file" $GAME:mac-intel
            elif [[ "$file" == *"silicon"* ]] || [[ "$file" == *"aarch64"* ]]; then
              ./butler push "$file" $GAME:mac-apple
            else
              ./butler push "$file" $GAME:mac
            fi
          done
